sudo: false
language: node_js
script: make test
node_js:
- 0.12.7
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: strategic.products@ft.com
  api_key:
    secure: eWONTWonq7UdF7JR4Ap4xh9fcpZYU3+C2fJFdzKT67mrK7YWJ0/CSJ3+Z6UECSnxgeh3/QzWMVrddaCxR+Ds4m23VqYT5R1+5kbaQBVzf4HlUgySpoz9tB+vE3hPLhopJOHt/fP+bPDQU+JDGcV0109E6c/AIoUl71N9tm92SSY=
  on:
    tags: true
    repo: Financial-Times/next-logger
